#ifndef SCRIPT_H
#define SCRIPT_H

constexpr u32 MAX_SCRIPTS = 64;
constexpr u32 MAX_SCRIPT_PROPERTIES = 16;

// Structs tagged ILU_STRUCT(Script) are the ones that can be registered as scripts
#define SCRIPT_HINT "Script"
constexpr u32 SCRIPT_INSTANCE_ALIGN = 16;

// A script component carries its instance data inline, so this bounds how large a
// registered script struct may be. RegisterScript refuses anything above it.
constexpr u32 MAX_SCRIPT_INSTANCE_SIZE = 256;

enum ScriptHookType
{
	ScriptHook_Start,
	ScriptHook_Simulate,
	ScriptHook_Update,
	ScriptHook_Stop,
	ScriptHook_Count,
};

typedef ReflexFunctor ScriptHook;

struct ScriptPropertyDesc
{
	const char *name;
	PropertyValue value;
};

struct ScriptDesc
{
	const char *name;
	u32 propertyCount;
	ScriptPropertyDesc properties[MAX_SCRIPT_PROPERTIES];
};

struct Script
{
	const ReflexStruct *type; // Layout and properties, generated by reflex
	ScriptHook hooks[ScriptHook_Count];
};

inline const char *ScriptName(const Script &script)
{
	return script.type->name;
}

inline u32 ScriptInstanceSize(const Script &script)
{
	return AlignUp((u32)script.type->size, SCRIPT_INSTANCE_ALIGN);
}

struct ScriptComponent
{
	const char *name; // Interned, and what a reload re-resolves structIndex from
	u16 structIndex;  // U16_MAX once the script is gone after a reload
	alignas(SCRIPT_INSTANCE_ALIGN) byte data[MAX_SCRIPT_INSTANCE_SIZE];
};

////////////////////////////////////////////////////////////////////////
// Binary data

#pragma pack(push, 1)

struct BinScriptPropertyDesc
{
	const char *name;
	ReflexID type;
	u32 value; // Raw view of PropertyValue, whichever member the type selects
};

struct BinScriptDesc
{
	const char *name;
	u32 propertyCount;
	BinScriptPropertyDesc properties[MAX_SCRIPT_PROPERTIES];
};

#pragma pack(pop)

#endif // SCRIPT_H
