#ifndef SCRIPT_H
#define SCRIPT_H

constexpr u32 MAX_SCRIPTS = 64;
constexpr u32 MAX_SCRIPT_PROPERTIES = 16;

// Structs tagged ILU_STRUCT(Script) are the ones that can be registered as scripts
#define SCRIPT_HINT "Script"
constexpr u32 SCRIPT_DATA_ALIGN = 16;

constexpr u32 SCRIPT_SIZE_CLASS_COUNT = 64;
constexpr u32 MAX_POOLED_SCRIPT_DATA_SIZE = SCRIPT_SIZE_CLASS_COUNT * SCRIPT_DATA_ALIGN;
constexpr u32 SCRIPT_DATA_MEMORY = MB(1);

enum ScriptHookType
{
	ScriptHook_Start,
	ScriptHook_Simulate,
	ScriptHook_Update,
	ScriptHook_Stop,
	ScriptHook_Count,
};

typedef ReflexFunctor ScriptHook;

struct ScriptPropertyDesc
{
	const char *name;
	PropertyValue value;
};

struct ScriptDesc
{
	const char *name;
	u32 propertyCount;
	ScriptPropertyDesc properties[MAX_SCRIPT_PROPERTIES];
};

struct Script
{
	const ReflexStruct *type; // Layout and properties, generated by reflex
	ScriptHook hooks[ScriptHook_Count];
};

inline const char *ScriptName(const Script &script)
{
	return script.type->name;
}

inline u32 ScriptDataSize(const Script &script)
{
	return AlignUp((u32)script.type->size, SCRIPT_DATA_ALIGN);
}

struct ScriptComponent
{
	const char *name; // Interned, and what a reload re-resolves structIndex from
	u16 structIndex;  // U16_MAX until a script is assigned, and again if a reload drops it
	u32 dataSize;     // Which bucket data returns to, still known once the script is gone
	byte *data;
};

struct ScriptDataBlock
{
	ScriptDataBlock *next;
};

// a block is never smaller than the link it has to store while it waits in a bucket.
CT_ASSERT(SCRIPT_DATA_ALIGN >= sizeof(void*));

struct ScriptDataPool
{
	Arena arena;
	ScriptDataBlock *freeLists[SCRIPT_SIZE_CLASS_COUNT];
};

////////////////////////////////////////////////////////////////////////
// Binary data

#pragma pack(push, 1)

struct BinScriptPropertyDesc
{
	const char *name;
	ReflexID type;
	u32 value; // Raw view of PropertyValue, whichever member the type selects
};

struct BinScriptDesc
{
	const char *name;
	u32 propertyCount;
	BinScriptPropertyDesc properties[MAX_SCRIPT_PROPERTIES];
};

#pragma pack(pop)

////////////////////////////////////////////////////////////////////////
// Functions

struct Engine;
struct Scene;

// The registry is rebuilt by RegisterScripts on every reload, so an index is only
// valid until the next one. Never hold one across a reload, hold the name instead.
void RegisterScripts();
u32 ScriptCount();
const Script &GetScriptAt(u32 index);

ScriptComponent *AddScript(Engine &engine, ID entityId);
ScriptComponent *SetScript(Engine &engine, ID entityId, const char *scriptName);
void SetScript(Engine &engine, ID entityId, const ScriptDesc &desc);
void RemoveScript(Engine &engine, ID entityId);
bool GatherEntityScriptDesc(const Scene &scene, ID entityId, ScriptDesc &outScript);
void RunScriptHooks(Engine &engine, ScriptHookType hook);
void RebindScripts(Engine &engine);

#endif // SCRIPT_H
